// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hoealuscfuqrmpzyambj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhvZWFsdXNjZnVxcm1wenlhbWJqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyNzQzNTksImV4cCI6MjA2Nzg1MDM1OX0.d2gmMD5_hyyS28bRPXU3Tr6cXnkTDt7tcHkSH7Yo8UE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});