// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rkqcnuosmlovfxujkkkc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJrcWNudW9zbWxvdmZ4dWpra2tjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0MTMwMDksImV4cCI6MjA2OTk4OTAwOX0.GuLLXUckBRo3QtqUFBmg3IHqYUqsIC8UYgrdptHDfaY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});